// Generated by scripts/sync.sh.

import categories from './data/categories.json' with { type: 'json' }
import groups from './data/groups.json' with { type: 'json' }
import _ from './data/technologies/_.json' with { type: 'json' }
import a from './data/technologies/a.json' with { type: 'json' }
import b from './data/technologies/b.json' with { type: 'json' }
import c from './data/technologies/c.json' with { type: 'json' }
import d from './data/technologies/d.json' with { type: 'json' }
import e from './data/technologies/e.json' with { type: 'json' }
import f from './data/technologies/f.json' with { type: 'json' }
import g from './data/technologies/g.json' with { type: 'json' }
import h from './data/technologies/h.json' with { type: 'json' }
import i from './data/technologies/i.json' with { type: 'json' }
import j from './data/technologies/j.json' with { type: 'json' }
import k from './data/technologies/k.json' with { type: 'json' }
import l from './data/technologies/l.json' with { type: 'json' }
import m from './data/technologies/m.json' with { type: 'json' }
import n from './data/technologies/n.json' with { type: 'json' }
import o from './data/technologies/o.json' with { type: 'json' }
import p from './data/technologies/p.json' with { type: 'json' }
import q from './data/technologies/q.json' with { type: 'json' }
import r from './data/technologies/r.json' with { type: 'json' }
import s from './data/technologies/s.json' with { type: 'json' }
import t from './data/technologies/t.json' with { type: 'json' }
import u from './data/technologies/u.json' with { type: 'json' }
import v from './data/technologies/v.json' with { type: 'json' }
import w from './data/technologies/w.json' with { type: 'json' }
import x from './data/technologies/x.json' with { type: 'json' }
import y from './data/technologies/y.json' with { type: 'json' }
import z from './data/technologies/z.json' with { type: 'json' }

export default {
  technologies: {
    ..._,
    ...a,
    ...b,
    ...c,
    ...d,
    ...e,
    ...f,
    ...g,
    ...h,
    ...i,
    ...j,
    ...k,
    ...l,
    ...m,
    ...n,
    ...o,
    ...p,
    ...q,
    ...r,
    ...s,
    ...t,
    ...u,
    ...v,
    ...w,
    ...x,
    ...y,
    ...z,
  },
  categories,
  groups,
}
